---
title: CB Genetics Github Repositories
---

## Project Repositories

To add your repository to this table, edit the table in the 01_project-repos.qmd file of the content folder of the [github repo for this landing page](https://github.com/noaa-nwfsc/CB_Genetics_Landing_Page). This is a quarto markdown file that creates this specific page and can be edited with basic markdown syntax (see General Github Resources and Glossary page if you need assistance). Remember you must push your commit to origin if working from desktop and the rendering and publishing (updating the webpage) will take a few minutes to complete.

| Project                                                                                            | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Data Input(s) | Contact Authors                               |
|----------------|--------------------------|----------------|----------------|
| [Vermilion Sunset Rockfish](https://github.com/noaa-nwfsc/vermilion-sunset-gtseq)                  | The primary objective was to conduct a genomic analysis to distinguish the vermilion rockfish stock along the west coast from sunset rockfish using tissue samples previously collected during fishery-independent resource surveys. Specifically, we (1) used high-throughput sequencing technologies to identify single nucleotide polymorphisms (SNPs) which produced an assay that definitively separates the two species, (2) applied this SNP panel to over 27 thousand samples and finally (3) identified species-specific demographic and biological differences. | GT-seq        | Anita Wray (anita.wray\@noaa.gov)             |
| [Eulachon RADseq](https://github.com/noaa-nwfsc/EulachonRADseq)                                    | Multi-year Eulachon RAD-seq analysis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | RADseq        | Mia Nahom (mia.nahom\@noaa.gov)               |
| [Wenatchee-RRS](https://github.com/noaa-nwfsc/Wenatchee-RRS)                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |               | Mike Ford (mike.ford\@noaa.gov)               |
| [Rockfish Metabarcoding](https://github.com/noaa-nwfsc/Rockfish-Metabarcoding)                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Metabarcoding | Meredith Everett (meredith.everett\@noaa.gov) |
| [qPCR_CPS](https://github.com/noaa-nwfsc/qPCR_CPS)                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |               | Michelle Hauer (michelle.hauer\@noaa.gov)     |
| [Chinook IRA Puget Sound Genomics](https://github.com/noaa-nwfsc/Chinook_IRA_Puget_Sound_Genomics) |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |               | Joanna Griffiths (joanna.griffiths\@noaa.gov) |

## Resource Repositories

| Repository                                              | Description                                                                                                                                                                                                                                                                                                                                                                                   | Reference/Contact                                                                                                                                                                                                                                                                                                                                                                                                               |
|----------------------|--------------------------------|-------------------|
| [GT-Score](https://github.com/gjmckinney/GTscore)       | Pipeline for GTseq genotyping and quality control                                                                                                                                                                                                                                                                                                                                             | Garrett McKinney                                                                                                                                                                                                                                                                                                                                                                                                                |
| [MarineOmics](https://marineomics.github.io/index.html) | A growing and evolving collection of guidelines, tutorials, recommended readings, and method evaluations for various ’omics analyses that are commonly used in studies of nonmodel systems (particularly marine species). Analysis examples include: WGS, low coverage WGS, reduced representation sequencing, Poolseq, RDA, PCA, ancient & degraded DNA, RNAseq, DNA methylation assessment. | Bogan, S. N., Johns, J., Griffiths, J. S., Davenport, D., Smith, S. J., Schaal, S. M., Downey-Wall, A., Lou, R. N., Lotterhos, K., Guidry, M. E., Rivera, H. E., McGirr, J. A., Puritz, J. B., Roberts, S. B., and Silliman, K. (2023). A dynamic web resource for robust and reproducible genomics in nonmodel species: marineomics.io. *Methods in Ecology and Evolution*, 00, 1–8. <https://doi.org/10.1111/2041-210X.14219> |
|                                                         |                                                                                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                                                                                 |
