---
title: Open Science
---

## What is Open Science?

Open science is a movement that aims to make scientific research, data, and publications available to everyone. It encourages collaboration, transparency, and productivity.

NOAA Fisheries has an Open Science Initiative with the intent to support scientists, developers, resource managers, and policy analysts in the adoption of modern, open, reproducible scientific workflows that enhance our already groundbreaking scientific work.This vision importantly also enables more timely fulfillment of NOAA’s Open Science mandates: 
* [NOAA Data Strategy](https://sciencecouncil.noaa.gov/wp-content/uploads/2022/08/2020-Data-Strategy.pdf)
* NOAA Fisheries Data Vision
* [DOC Open Source Code Policy](https://www.commerce.gov/about/policies/source-code)
* [Federal Data Strategy](https://strategy.data.gov/)
* [Federal Open Access Memo]
* [Open Government National Action Plan]

Information pulled from [Open Science at NOAA Fisheries](https://www.fisheries.noaa.gov/science-data/open-science-noaa-fisheries)

## NMFS Open Science Resources

NMFS Open Science [public home page](https://nmfs-opensci.github.io/)

NMFS Open Science [internal home page](https://sites.google.com/noaa.gov/nmfs-hq-st-open-science/home)
- Links to NMFS Open Science calendar of events

NMFS Open Science [Resource Book](https://nmfs-opensci.github.io/ResourceBook/)

NMFS Openscapes is a collaboration between NOAA Fisheries and Openscapes to promote a data-driven culture through the adoption of open science tools and strategies. Openscapes provides team-based training in reproducible scientific workflows, data management, coding, and optimal team collaboration and project management. Keep an eye out for upcoming openscapes champions cohort opportunities on their [webpage](https://nmfs-openscapes.github.io/).


